# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

os: Visual Studio 2019

platform:
  - x64

build_script:
  - mkdir tinyply_build
  - cd tinyply_build
  - cmake -G "Visual Studio 16 2019" ..
  - cmake --build . --config Release